name: gym
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_clean_calendar: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_swiper: ^1.1.6
  carousel_slider: ^4.0.0
  image_picker: ^0.8.5+3
  get: ^4.6.1
  fl_chart: ^0.50.6
  textfield_search: ^0.10.0
  flutter_custom_clippers: ^2.0.0
  flutter_switch: ^0.3.2
  auto_route: ^4.0.0
  share_plus: ^3.0.4
  intl: ^0.17.0
  table_calendar: ^2.3.3
  shared_preferences: ^2.0.13
  d_chart: ^0.0.4
  pin_code_fields: ^7.4.0
  google_fonts: ^3.0.1




















# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
     - assets/images/gym.jpg
     - assets/images/music.jpg
     - assets/images/Dil.jpg
     - assets/images/flag.jpg
     - assets/images/antivirus.jpg
     - assets/images/antiviours1.jpg
     - assets/images/google+.png
     - assets/images/facebook.png
     - assets/images/facebook3.png
     - assets/images/gym1.jpg
     - assets/images/gym logo.png
     - assets/images/gym2.jpg
     - assets/images/member.jpg
     - assets/images/star.png
     - assets/images/share.png
     - assets/images/debt.png
     - assets/images/documents.png
     - assets/images/presentation.png
     - assets/images/calendar(1).png
     - assets/images/money-exchange.png
     - assets/images/Member1.jpg
     - assets/images/7-days.png
     - assets/images/number-3.png
     - assets/images/number-15.png
     - assets/images/salary.png
     - assets/images/wallet.png
     - assets/images/celectric_repairing.jpeg
     - assets/images/Anniversary.jpg
     - assets/images/Birthday.jpg
     - assets/images/dollare.webp
     - assets/images/timer.png
     - assets/images/money.png
     - assets/images/gym3.jpg
     - assets/images/gym4.jpg
     - assets/images/gym5.jpg
     - assets/images/GYM6.jpg
     - assets/images/GYM7.jpg
     - assets/images/GYM8.jpg
     - assets/images/Subscription.png
     - assets/images/Need Help.png
     - assets/images/Refer Earn.png
     - assets/images/Master.png
     - assets/images/Enrollment fee.png
     - assets/images/Manage Plan.png
     - assets/images/Tax.png
     - assets/images/Master.png
     - assets/images/members(1).png
     - assets/images/newmember.webp
     - assets/images/member5.png
     - assets/images/gymmembers.jpg
     - assets/images/financial.jpg
     - assets/images/plan.jpg
     - assets/images/birthday1.jpg
     - assets/images/upcomingbirthday.jpg
     - assets/images/Batch.png
     - assets/images/Invoice.png
     - assets/images/Report.png
     - assets/images/Notice.png
     - assets/images/User Log.png
     - assets/images/Add Member.png
     - assets/images/Trainer.png
     - assets/images/Attendance.png
     - assets/images/Enquiry.png
     - assets/images/Attendance.png
     - assets/images/calendar.png
     - assets/images/information.png
     - assets/images/information(1).png
     - assets/images/messages.png
     - assets/images/diet.png
     - assets/images/exercise.png
     - assets/images/barbell.png
     - assets/images/plan.png
     - assets/images/question.png
     - assets/images/follow.png
     - assets/images/Doller.png
     - assets/images/SMS.png
     - assets/images/Diet Plan.png
     - assets/images/Excersice.png
     - assets/images/Measurement.png
     - assets/images/Manage Plan.png
     - assets/images/Communicate.png
     - assets/images/QR Code.png
     - assets/images/Theme.png
     - assets/images/Language.png
     - assets/images/Contact.png
     - assets/images/Logout.png
     - assets/images/gymlogo1.png
     - assets/images/members.png
     - assets/images/group.png
     - assets/images/wallet(1).png
     - assets/images/calendar.png
     - assets/images/cake.png
     - assets/images/expenses.png
     - assets/images/hand.png
     - assets/images/dollar.png
     - assets/images/planning.png
     - assets/images/health.png
     - assets/images/offer.png
     - assets/images/challenge.png
     - assets/images/branch.png
     - assets/images/Report.png
     - assets/images/settings.png
     - assets/images/plans.png
     - assets/images/new-offer.png
     - assets/images/rupee.png
     - assets/images/add-user.png
     - assets/images/add-user(1).png
     - assets/images/money1.png
     - assets/images/transaction.png
     - assets/images/reminder.jpg
     - assets/images/new-offer1.png
     - assets/images/goal.png
     - assets/images/target.png
     - assets/images/giftbox.png
     - assets/images/trophy.png
     - assets/images/winner.webp
     - assets/images/winner2.webp
     - assets/images/gymchallange.jpg
     - assets/images/gymchallange1.webp
     - assets/images/gymchallange2.webp
     - assets/images/gymchallange3.webp
     - assets/images/refer.jpg
     - assets/images/whatsapp.png
     - assets/images/ic_facebook.png
     - assets/images/more.png
     - assets/images/instagram.png
     - assets/images/more(1).png
     - assets/images/whatsapp(1).png
     - assets/images/running.jpg
     - assets/images/running1.jpg
     - assets/images/running2.webp
     - assets/images/running3.webp
     - assets/images/running4.jpg
     - assets/images/arms.jpg
     - assets/images/arms1.jpg
     - assets/images/arms2.webp
     - assets/images/arms3.jpeg
     - assets/images/chest.jpg
     - assets/images/chest1.webp
     - assets/images/chest2.webp
     - assets/images/chest3.webp
     - assets/images/chest4.jpg
     - assets/images/back.jpg
     - assets/images/back1.png
     - assets/images/back2.jpg
     - assets/images/back3.webp
     - assets/images/login1.png
     - assets/images/login2.png
     - assets/images/login3.png
     - assets/images/register.png
     - assets/images/abstract1.png
     - assets/images/background.jpg
     - assets/images/My project.png
     - assets/images/My project(1).png
     - assets/images/Nutrition_food2.jpg
     - assets/images/Nutrition_food3.jpg
     - assets/images/burger.jpg
     - assets/images/Laccha_pratha.jpg
     - assets/images/Laccha_pratha3.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
